//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            Image = "~/AppFiles/Images/default.png";
        }


        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public int ProuductID { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$")]
        public string ProductName { get; set; }
        [Required]
        [RegularExpression(@"-?\d+(?:\.\d+)?")]
        public Nullable<decimal> Price { get; set; }
        [RegularExpression(@"^(?:[3|4])$")]
        [Required]
        public Nullable<int> TypeID { get; set; }

        public string Image { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$")]
        public string Description { get; set; }
        public Nullable<int> StatusID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeUser TypeUser { get; set; }
    }
}

/*

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            Image = "~/AppFiles/Images/default.png";
        }


        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public int ProuductID { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$")]
        public string ProductName { get; set; }
        [Required]
        [RegularExpression(@"^\d+(\.\d\d)?$")]
        public Nullable<decimal> Price { get; set; }
        [RegularExpression(@"^(?:[3|4])$")]
        [Required]
        public Nullable<int> TypeID { get; set; }

        [Required]
        public string Image { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$")]
        public string Description { get; set; }
        [Required]
        public Nullable<int> StatusID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeUser TypeUser { get; set; }
    }
}
*/
